label tracydate:
    "I free myself from Isabelle's grip and pretend to go back downstairs."
    "Isabelle goes into the bathroom."
    "I take the opportunity to return to the room and close the door behind me."
    "Tracy is on the bed, looking at her phone."
    "I sit down next to her and she puts her phone away."
    tra "So, what do you want to do?"
    name "I don't know."
    name "We could play cards or something."
    tra "Cards? Really?"
    name "Haha, I don't know."
    name "I don't know what we're supposed to do in this kind of situation."
    tra "Don't pretend."
    name "Won't Mélanie be upset that we're in the room together?"
    tra "Probably..."
    tra "But like I said, we're not really together so it's fine."
    tra "At least I think so."
    name "Maybe we could just talk?"
    name "That way you don't ruin your plan."
    tra "Yeah..."
    tra "Soo... "
    name "Ask me a question?"
    tra "Ok so"
    tra "If you could "
    tra "If you could travel anywhere in the world right now, where would you go and why?"
    name "Japan, I think."
    tra "Come on, everyone wants to go to Japan"
    tra "It's like the most popular destination right now."
    name "Why?"
    tra "Everyone wants to go to Japan."
    name "Would you go?"
    tra "I don't know, maybe Colombia."
    name "Colombia? Why?"
    tra "It's a really beautiful country."
    name "Really?"
    tra "Yeah, I saw a documentary about it, it looks amazing."
    tra "It's the country of the Incas."
    tra "I'd really love to visit the archaeological ruins over there."
    name "Is this the moment where I suggest we go together?"
    tra "Haha, I don't know, that's up to you."
    name "Let's leave right now! Let's leave this party behind us."
    tra "Haha, stop it, you're making me feel like I'm in a movie."
    name "But seriously, it would be great to go there."
    tra "Give me your number. If I need a travel companion, I'll call you."
    name "Sure, here..."
    "I give Tracy my number."
    tra "Thanks, now I can harass you."
    tra "You fell into my trap."
    name "Oh no."
    tra "Do you have any last wishes?"
    name "I think i do."
    "Tracy moves closer to me and kisses me."
    "We lie down on the bed, kissing."
    "Her lipstick is soft and sweet."
    "I feel her hands on my body, she caresses me gently."
    "Her perfume is soothing."
    "I close my eyes, enjoying the moment."
    "Our breaths mingle, time seems to stand still."
    "Tracy looks at me tenderly, a slight smile on her lips."
    "I feel my heart beating faster as she holds me close."
    "We stay like this, cuddled up together, forgetting the rest of the world."
    "..."
    "We stay here for half an hour, kissing and cuddling."
    "We eventually get up, a little embarrassed."
    "Tracy reçoit une message sur son téléphone."
    "Melanie lui demande où elle est."

    tra "It's Mel"
    "Tracy reads the message and smiles."
    tra "She wants to know where I am."
    "Tracy replies that she's with me and that we're talking."
    "Tracy sends the message and puts her phone away."
    tra "I think we should go back downstairs."
    name "Yeah, I think so too."
    "We get up and leave the room."
    "Downstairs, Tracy finds Mélanie and tells her she was with me."
    "Mélanie looks at us with a knowing smile."
    "She comes closer to me."
    mel "So, how was it?"
    name "What do you mean?"
    mel "Don't worry, your secret is safe with me, haha."
    "I laugh awkwardly, not really knowing what to say."
    "Tracy and Mélanie exchange a look, Tracy comes to snuggle against Mélanie."
    "Mélanie strokes her hair."
    "I watch them, not really knowing what to do."
    "I feel a bit weird."
    "Mélanie gives her a playful slap on the cheek."
    mel "Naughty."
    "Tracy blushes and looks down."
    mel "Come on, let's go upstairs."
    "Mélanie takes Tracy's hand and leads her upstairs."
    "I watch them leave, feeling a bit lost."
    "Tracy looks at me, both embarrassed and excited."
    "Maybe I should follow them?"




    label tracydate2:
        "I follow them upstairs."
        "I gently open the bedroom door."
        "I peek inside."
        "I find them in the room where we were before."
        "Tracy is sitting on the bed, Mélanie is standing next to her."
        "Mélanie has her pants down and is showing her dick to Tracy."
        "Tracy is slowly sucking her."
        mel "That's it."
        mel "Do what you do best."
        mel "Did you think you could escape me?"
        "Etc etc...."