label camilleuni_date:
    scene upview3 with dissolve
    "We enter the café, and Camille guides me to a table by the window."
    "She greets her friend and introduces me to her."

    scene camilldeunidate19 with dissolve
    cam "This is Amy"
    name "Nice to meet you"
    "Amy smiles warmly, her eyes sparkling with curiosity."
    amy "Nice to meet you too"
    scene camilldeunidate17 with dissolve
    "Amy and Camille dive into conversation about their blog and upcoming ideas."
    "They exchange the latest gossip, critiquing various influencers and debating current trends."
    "I listen quietly, enjoying the dynamic between them."
    scene camilldeunidate18 with dissolve
    "They clearly know each other well, and I don't mind being an observer."
    "Though I can't help feeling a bit forgotten in their animated discussion."
    "I glance around the café, watching other customers come and go."
    "After a while, Amy turns to me with a friendly smile."
    scene camilldeunidate14 with dissolve
    amy "How's your coffee?"
    name "It's really good, thanks."
    name "Sorry, I was trying to follow but there were too many names and brands I don't know."
    name "So I didn't really follow along."
    amy "ahah, no problem!"
    amy "We can talk about something else."
    amy "So, how did you two meet?"
    scene camilldeunidate20 with dissolve
    "Camille seems amused by the question."
    cam "We met in class..."
    cam "He was sitting next to me, and I thought he looked like a nice guy."
    cam "So I decided to be nice to him."
    amy "Really? Camille being nice to someone?"
    "Camille rolls her eyes playfully."
    amy "So you study art history is that right?"
    name "yep and you?"
    amy "I'm studying psychology."
    amy "I love understanding how people think and behave."
    name "Yeah i bet."
    amy "It's fascinating."
    amy "And on the side I'm a fashion fan, so we started a blog with Camille."
    name "That's cool. Do your courses help with the blog?"
    amy "Not always, but I sometimes use psychological concepts to analyze trends and people's behavior."
    amy "And it can help with relationships too."
    name "Ah yeah, I see."
    cam "Amy sees people like lab rats."
    cam "She's mentally working on a case study every time she meets someone."
    cam "She told me that once."
    amy "Haha, come on, I don't do that with everyone."
    amy "Just sometimes there are interesting cases."
    cam "She won't tell you, but in her head, you're already a study subject."
    cam "She's picturing you running on a wheel."
    amy "No way, not at all!"
    name "Haha, I don't mind being a subject of study."
    cam "yeah but you don't know what she's studying."
    cam "She'll make you do weird stuff."  
    cam "And you'll wake up with a plastic object in your ass"
    amy "ahahah."
    if gender == "male":
        cam "Maybe he'll like it."
    elif gender == "fem":
        cam "Maybe she'll like it."
    amy "No, no, I promise I won't do anything weird."
    name "I hope."

    amy "The people I like to study are usually those in the fashion world."
    amy "I swear it's really fascinating to watch."
    cam "I bet there are plenty of people we meet who would love to become your lab animals."
    "Camille and Amy continue to joke about psychology and fashion, their laughter filling the café."
    "The vibe gets way more chill as we keep talking."
    "Amy starts asking me about stuff I do outside school."
    "Time flies by while we're just chatting about random things."
    "Then Amy checks her phone and her eyes go wide."
    amy "Oh shit, I totally lost track of time."
    amy "I gotta meet my study group in like twenty minutes."
    "She starts grabbing her stuff."
    amy "This was fun!"
    amy "We should totally do this again."
    name "Yeah, for sure. It was cool meeting you."
    cam "I'll hit you up later, Amy."
    "Amy waves and rushes out of the café."
    "Now it's just me and Camille at the table."
    cam "She totally liked you, I could tell."
    "Camille grins and takes another sip of her coffee."
    cam "Wanna head back?"
    name "Yeah, let's go."
    "We finish up and head out of the café."
    cam "It was cool hanging out."
    cam "We should do this again sometime."
    name "Yeah, definitely."
    name "See you."
    cam "See you, lab rat."
    
    $ classdatecamille_count += 1
    $ class_done = True
    scene black with dissolve
    "I head back to the garden."
    jump gardenuni_start2

